replicaCount: 1

image:
  repository: scr.sitecore.com/sxp/sitecore-id6
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "10.2-ltsc2019"

imagePullSecrets: 
  - name: sitecore-docker-registry
nameOverride: ""
fullnameOverride: "sitecore-id"


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources:
  requests:
    memory: 700Mi
    cpu: 200m
  limits:
    memory: 1Gi
    cpu: 300m

nodeSelector: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80