# This is a basic workflow to help you get started with Actions

name: _create-release

# Controls when the workflow will run
on:
  workflow_call: 
    inputs:
      version:
        required: true
        type: string
      pre_release:
        required: true
        type: boolean
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "build"
  create-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
              
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ inputs.version }}
          release_name: Release v.${{ inputs.version }}
          body: |
            ${{ github.event.head_commit.message }}
          prerelease: ${{ inputs.pre_release }}
