apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: c18d6e7b-c245-42e0-b7e9-f249cfa3714b
  labels:
    azure.workload.identity/use: "true"
  name: sitecore-default-sa
  namespace: default