# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
  namespace: default
spec:
  provider: azure
  secretObjects: # Create a Kubernetes Secret
    - secretName: "general" # Change this
      type: Opaque
      data:
        - objectName: "foo"
          key: "psw"
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"    # Set to true for using managed identity
    clientID: "c18d6e7b-c245-42e0-b7e9-f249cfa3714b"      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: sitecore-secrets
    cloudName: "AzurePublicCloud"                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: foo
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    tenantId: ff0cf4cd-4b0b-4c4c-ae5d-b87d0905fdb1          # The tenant ID of the key vault