{{- $fullName := include "rendering.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "rendering.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "rendering.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}