name: _deploy-helm-package

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      helm_repo_url:
        required: false
        type: string      
      
      helm_repo_name:
        required: false
        type: string        
        
      args:
        required: true
        type: string
        
      chart_name:
        required: true
        type: string
        
      environment:
        required: true
        type: string
        default: 'dev'
          
      namespace:
        required: true
        type: string
        default: sitecore
        
      working-directory:
          required: false
          type: string
          default: '.'
        
    secrets:
      AZURE_CREDENTIALS:
        required: true
      RESOURCE_GROUP:
        required: true
      CLUSTER_NAME:
        required: true
      SUBSCRIPTION_ID:
        required: true
      HELM_USERNAME:
        required: false
      HELM_PASSWORD:
        required: false
      
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    environment: ${{ inputs.environment }}
    
    steps:
    
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          subscription: ${{ secrets.SUBSCRIPTION_ID }}
          admin: true
      
      - name: Helm tool installer
        uses: Azure/setup-helm@v3.3
        with:
          version: 3.9.0
          
      - name: Add Helm repository
        shell: pwsh
        run: |
          $params = @('${{ inputs.helm_repo_name }}', '${{ inputs.helm_repo_url }}')
          if(${{ secrets.HELM_USERNAME }}) {$params = $params + '--username=${{ secrets.HELM_USERNAME }}'}
          if(${{ secrets.HELM_PASSWORD }}) {$params = $params + '--username=${{ secrets.HELM_PASSWORD }}'}
          #helm repo add ${{ inputs.helm_repo_name }} ${{ inputs.helm_repo_url }} --username ${{ secrets.HELM_USERNAME }} --password ${{ secrets.HELM_PASSWORD }}
          write-host $params
          helm repo add @params
          #helm repo update ${{ inputs.helm_repo_name }}
      
      #- name: Deploy ${{ inputs.chart_name }} chart 
      #  shell: bash
      #  run: |
      #    helm pull ${{ inputs.helm_repo_name }}/${{ inputs.chart_name }} --untar
      #    helm upgrade --install --atomic --timeout 10m0s -n ${{ inputs.namespace }} ${{ inputs.args }} ${{ inputs.chart_name }} ${{ inputs.helm_repo_name }}/${{ inputs.chart_name }}
      
      
      - name: logout
        if: always()
        run: |
          az logout
