name: Deploy Sitecore

on:  
  workflow_dispatch: 
    inputs:
      environment:
        description: 'Environment to run build and deploy against'
        type: environment
        required: true 

jobs:  
  deploy-sitecore:    
    uses: ./.github/workflows/_deploy-helm-package-to-aks.yml
    secrets: 
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      RESOURCE_GROUP: ${{secrets.RESOURCE_GROUP}}
      CLUSTER_NAME: ${{secrets.CLUSTER_NAME}}
      SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
      ARGS: -f ./sitecore-xm1-103/values.yaml -f ./sitecore-xm1-103/values-xm1.yaml      
    with:
      helm_repo_url: https://ampach.github.io/Helm-Charts
      helm_repo_name: ampach
      chart_name: sitecore-xm1-103
      namespace: default
      environment: ${{ inputs.environment }}
