name: Init Sitecore

on:  
  workflow_dispatch: 
    inputs:
      environment:
        description: 'Environment to run build and deploy against'
        type: environment
        required: true 

jobs:

  cluster-init:    
    uses: ./.github/workflows/_deploy-helm-package.yml
    secrets: 
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
    with: 
      helm_repo_url: http://test.cor
      helm_repo_name: workflow
      args: -f ./sitecore-init/values.yaml -f ./sitecore-init/values-aks-${{ inputs.environment }}.yaml --set init-mssql.image.tag=${{ vars.SITECORE_VERSION }}
      chart_name: sitecore-init2
      environment: ${{ inputs.environment }}
      namespace: sitecore
